export const icons = {
    flashcard: "⧉",
    gril: "⊞",
    focus: "⌖",
    diamondFull: "◈",
    diamondOutline: "⟐",
    squareDot: "⊡",
    exagon: "⎔",
    target: "⊹",
    pencil: "✎",
    arrowsBidirectional: "⇄",
    update: "↺",
    block: "⊘",
    ellipsis: "⋯",
    cancel: "⌦",
    upArrow: "⏶",
    circledAsterix: "⊛",
    // Audio / Sound
    speaker: "🕨",
    speakerLow: "🕩",
    speakerHigh: "🕪",
    bullhorn: "🕫",
    bullhornActive: "🕬",
    bell: "🕭",

    // Objects
    book: "🕮",
    candle: "🕯",
    clock: "🕰",
    skull: "🕱",
    noPiracy: "🕲",
    hole: "🕳",

    // Accessories / Nature
    sunglasses: "🕶",
    spider: "🕷",
    spiderWeb: "🕸",

    // Gaming / Entertainment
    joystick: "🕹",

    // Phone / Communication
    phonLeft: "🕻",
    phoneWithPage: "🕼",
    phoneRight: "🕽",
    phoneTouchWhite: "🕾",
    phoneTouchBlack: "🕿",
    phoneOnModem: "🖀",
    mobilePhone: "🖁",

    // Mail / Envelopes
    envelope: "🖂",
    envelopeStamped: "🖃",
    envelopeLightning: "🖄",
    envelopeFlying: "🖅",
    envelopePen: "🖆",

    // Office / Stationery
    paperclips: "🖇",
    pushpin: "🖈",
    pencil: "🖉",
    pen: "🖊",
    fountainPen: "🖋",
    paintbrush: "🖌",
    crayon: "🖍",

    // Hands / Gestures
    writingHand: "🖎",
    okHand: "🖏",
    handSplayedReversed: "🖑",
    thumbsUp: "🖒",
    thumbsDown: "🖓",
    victory: "🖔",
    pointDownLeft: "🖗",
    pointLeftWhite: "🖘",
    pointRightWhite: "🖙",
    pointLeftBlack: "🖚",
    pointRightBlack: "🖛",
    backhandLeft: "🖜",
    backhandRight: "🖝",
    pointUpWhite: "🖞",
    pointDownWhite: "🖟",
    pointUpBlack: "🖠",
    pointDownBlack: "🖡",
    backhandUp: "🖢",
    backhandDown: "🖣",

    // Computer / Tech
    desktop: "🖥",
    keyboardAndMouse: "🖦",
    network: "🖧",
    printer: "🖨",
    calculator: "🖩",
    floppyBlack: "🖪",
    floppyWhite: "🖫",
    floppySoft: "🖬",
    tapeCartridge: "🖭",
    keyboard: "🖮",
    mouseOneButton: "🖯",
    mouseTwoButton: "🖰",
    mouseThreeButton: "🖱",
    trackball: "🖲",
    oldComputer: "🖳",
    hardDisk: "🖴",
    screen: "🖵",
    printerIcon: "🖶",
    fax: "🖷",
    opticalDisc: "🖸",

    // Documents / Files
    documentText: "🖹",
    documentTextAndPicture: "🖺",
    documentPicture: "🖻",
    frame: "🖼",
    frameTiles: "🖽",
    frameX: "🖾",
    folderClosed: "🖿",
    folder: "🗀",
    folderOpen: "🗁",
    cardIndexDividers: "🗂",
    cardFileBox: "🗃",
    fileCabinet: "🗄",
    noteEmpty: "🗅",
    notePageEmpty: "🗆",
    notePadEmpty: "🗇",
    note: "🗈",
    notePage: "🗉",
    notePad: "🗊",
    documentEmpty: "🗋",
    pageEmpty: "🗌",
    pagesEmpty: "🗍",
    document: "🗎",
    page: "🗏",
    pages: "🗐",
    wastebasket: "🗑",
    spiralNotepad: "🗒",
    spiralCalendar: "🗓",

    // UI / Window Controls
    desktopWindow: "🗔",
    minimize: "🗕",
    maximize: "🗖",
    overlap: "🗗",
    refresh: "🗘",
    close: "🗙",
    increaseFontSize: "🗚",
    decreaseFontSize: "🗛",
    compress: "🗜",
    oldKey: "🗝",
    newspaper: "🗞",
    pageCircled: "🗟",

    // Misc
    stockChart: "🗠",
    dagger: "🗡",
    lips: "🗢",
    speakingHead: "🗣",

    // Rays
    raysAbove: "🗤",
    raysBelow: "🗥",
    raysLeft: "🗦",
    raysRight: "🗧",

    // Speech / Thought Bubbles
    speechBubbleLeft: "🗨",
    speechBubbleRight: "🗩",
    speechBubbles: "🗪",
    speechBubblesThree: "🗫",
    thoughtBubbleLeft: "🗬",
    thoughtBubbleRight: "🗭",
    angerBubbleLeft: "🗮",
    angerBubbleRight: "🗯",
    moodBubble: "🗰",
    lightningMoodBubble: "🗱",
    lightningMood: "🗲",

    // Voting / Checkmarks
    ballotBox: "🗳",
    ballotX: "🗴",
    ballotBoxX: "🗵",
    ballotBoldX: "🗶",
    ballotBoxBoldX: "🗷",
    checkLight: "🗸",
    checkBold: "🗹",

    // Geography
    worldMap: "🗺",
};
