import type { Scenario } from "./types";

export const scenarios: Scenario[] = [
    // ── Ramo green ────────────────────────────────────────────────────────────
    {
        id: "s-verde-1",
        type: "scenario",
        vignette: "Il paziente è cosciente e cammina verso di te chiedendo aiuto.",
        correctAnswer: "red",
        options: ["green", "yellow", "red"],
        explanation: "Cammina → green. Il paziente deambulante viene classificato immediatamente senza ulteriori valutazioni.",
        path: ["Cammina? → SÌ", "→ green"],
    },
    {
        id: "s-verde-2",
        type: "scenario",
        vignette: "Una donna urla il nome del marito e si avvicina di corsa alla scena dell'incidente.",
        correctAnswer: "green",
        options: ["green", "yellow", "red"],
        explanation: "Cammina autonomamente → green, indipendentemente dallo stato emotivo.",
        path: ["Cammina? → SÌ", "→ green"],
    },
    {
        id: "s-verde-3",
        type: "scenario",
        vignette: "Un uomo con una ferita lacera alla mano si avvicina zoppicando ma in modo autonomo.",
        correctAnswer: "green",
        options: ["green", "yellow", "red"],
        explanation: "Cammina, anche se con difficoltà → green. Il criterio è la deambulazione autonoma, non la qualità dell'andatura.",
        path: ["Cammina? → SÌ", "→ green"],
    },

    // ── Ramo red: non respira, cannula fallisce ─────────────────────────────
    {
        id: "s-rosso-cannula-1",
        type: "scenario",
        vignette: "Il paziente è a terra, non cammina e non respira. Dopo pervietà-cannula non inizia a respirare.",
        correctAnswer: "red",
        options: ["green", "yellow", "red"],
        explanation: "Non respira → pervietà-cannula → ancora non respira → red.",
        path: ["Cammina? → NO", "Respira? → NO", "Pervietà-cannula → respira? → NO", "→ red"],
    },
    {
        id: "s-rosso-cannula-2",
        type: "scenario",
        vignette: "Paziente incosciente, apnea. Inserita la cannula: nessun movimento respiratorio apprezzabile dopo 10 secondi.",
        correctAnswer: "red",
        options: ["green", "yellow", "red"],
        explanation: "Cannula senza ripresa respiratoria → red immediato.",
        path: ["Cammina? → NO", "Respira? → NO", "Pervietà-cannula → respira? → NO", "→ red"],
    },

    // ── Ramo red: non respira, cannula funziona ma freq > 30 ───────────────
    {
        id: "s-rosso-freq-alta-1",
        type: "scenario",
        vignette: "Paziente supino, non cammina. Dopo pervietà-cannula riprende a respirare con frequenza di 34 atti/min.",
        correctAnswer: "red",
        options: ["green", "yellow", "red"],
        explanation: "Respira dopo cannula ma > 30 atti/min → red.",
        path: ["Cammina? → NO", "Respira? → NO", "Pervietà-cannula → respira? → SÌ", "> 30 atti/min? → SÌ", "→ red"],
    },

    // ── Ramo red: respira spontaneamente ma freq > 30 ──────────────────────
    {
        id: "s-rosso-freq-alta-2",
        type: "scenario",
        vignette: "Il paziente non cammina, respira spontaneamente con frequenza di 36 atti/min.",
        correctAnswer: "red",
        options: ["green", "yellow", "red"],
        explanation: "Respira ma > 30 atti/min → red. L'alta frequenza è già sufficiente.",
        path: ["Cammina? → NO", "Respira? → SÌ", "< 30 atti/min? → NO", "→ red"],
    },
    {
        id: "s-rosso-freq-alta-3",
        type: "scenario",
        vignette: "Donna a terra, non si alza. Respira in modo affannoso e superficiale: conti 32 atti in un minuto.",
        correctAnswer: "red",
        options: ["green", "yellow", "red"],
        explanation: "32 atti/min > 30 → red senza proseguire la valutazione.",
        path: ["Cammina? → NO", "Respira? → SÌ", "< 30 atti/min? → NO", "→ red"],
    },
    {
        id: "s-rosso-freq-alta-4",
        type: "scenario",
        vignette: "Paziente agitato, non si rialza. La respirazione è rapida: stimi circa 40 atti/min.",
        correctAnswer: "red",
        options: ["green", "yellow", "red"],
        explanation: "~40 atti/min → nettamente > 30 → red.",
        path: ["Cammina? → NO", "Respira? → SÌ", "< 30 atti/min? → NO", "→ red"],
    },

    // ── Ramo red: freq ok, polso assente ───────────────────────────────────
    {
        id: "s-rosso-polso-1",
        type: "scenario",
        vignette: "Il paziente non cammina. Respira a 22 atti/min. Non riesci ad apprezzare il polso radiale.",
        correctAnswer: "red",
        options: ["green", "yellow", "red"],
        explanation: "Frequenza ok → polso assente → red.",
        path: ["Cammina? → NO", "Respira? → SÌ", "< 30 atti/min? → SÌ", "Polso radiale? → NO", "→ red"],
    },
    {
        id: "s-rosso-polso-2",
        type: "scenario",
        vignette: "Paziente in posizione laterale, non si muove. FR 18/min. Al polso radiale non percepisci alcun battito dopo 5 secondi di ricerca.",
        correctAnswer: "red",
        options: ["green", "yellow", "red"],
        explanation: "Polso radiale assente → red, indipendentemente dalla frequenza respiratoria.",
        path: ["Cammina? → NO", "Respira? → SÌ", "< 30 atti/min? → SÌ", "Polso radiale? → NO", "→ red"],
    },
    {
        id: "s-rosso-polso-3",
        type: "scenario",
        vignette: "Non cammina, FR 25/min, polso radiale assente. Presenta un'emorragia evidente alla coscia.",
        correctAnswer: "red",
        options: ["green", "yellow", "red"],
        explanation: "Polso assente → red. L'emorragia non modifica il codice in questa fase — il polso assente chiude il ramo.",
        path: ["Cammina? → NO", "Respira? → SÌ", "< 30 atti/min? → SÌ", "Polso radiale? → NO", "→ red"],
    },

    // ── Ramo red: tutto ok ma non esegue ordini ─────────────────────────────
    {
        id: "s-rosso-ordini-1",
        type: "scenario",
        vignette: "Non cammina. FR 20/min. Polso radiale presente. Quando dici 'stringimi la mano' non c'è risposta.",
        correctAnswer: "red",
        options: ["green", "yellow", "red"],
        explanation: "Ordini semplici non eseguiti → red.",
        path: ["Cammina? → NO", "Respira? → SÌ", "< 30 atti/min? → SÌ", "Polso radiale? → SÌ", "Ordini semplici? → NO", "→ red"],
    },
    {
        id: "s-rosso-ordini-2",
        type: "scenario",
        vignette: "Paziente a terra, paramteri respiratori e circolatori nella norma. Gli chiedi di aprire gli occhi: nessuna risposta.",
        correctAnswer: "red",
        options: ["green", "yellow", "red"],
        explanation: "Apertura occhi su comando = ordine semplice. Non eseguito → red.",
        path: ["Cammina? → NO", "Respira? → SÌ", "< 30 atti/min? → SÌ", "Polso radiale? → SÌ", "Ordini semplici? → NO", "→ red"],
    },
    {
        id: "s-rosso-ordini-3",
        type: "scenario",
        vignette: "FR 16/min, polso radiale valido. Il paziente geme ma non risponde ad alcun comando verbale.",
        correctAnswer: "red",
        options: ["green", "yellow", "red"],
        explanation: "Gemito non equivale a eseguire ordini. Ordini non eseguiti → red.",
        path: ["Cammina? → NO", "Respira? → SÌ", "< 30 atti/min? → SÌ", "Polso radiale? → SÌ", "Ordini semplici? → NO", "→ red"],
    },

    // ── Ramo yellow ───────────────────────────────────────────────────────────
    {
        id: "s-giallo-1",
        type: "scenario",
        vignette: "Non cammina. FR 22/min. Polso radiale presente. Stringe la mano al comando.",
        correctAnswer: "yellow",
        options: ["green", "yellow", "red"],
        explanation: "Tutti i parametri nella norma, esegue ordini → yellow.",
        path: ["Cammina? → NO", "Respira? → SÌ", "< 30 atti/min? → SÌ", "Polso radiale? → SÌ", "Ordini semplici? → SÌ", "→ yellow"],
    },
    {
        id: "s-giallo-2",
        type: "scenario",
        vignette: "Paziente seduto a terra, non si alza. FR 17/min, polso radiale ritmico. Apre gli occhi e indica la gamba dolente su richiesta.",
        correctAnswer: "yellow",
        options: ["green", "yellow", "red"],
        explanation: "Esegue ordini semplici (indica su richiesta) → yellow.",
        path: ["Cammina? → NO", "Respira? → SÌ", "< 30 atti/min? → SÌ", "Polso radiale? → SÌ", "Ordini semplici? → SÌ", "→ yellow"],
    },
    {
        id: "s-giallo-3",
        type: "scenario",
        vignette: "Donna con probabile frattura alla gamba, non deambula. Respira tranquillamente a 14/min. Polso radiale presente, risponde a domande semplici.",
        correctAnswer: "yellow",
        options: ["green", "yellow", "red"],
        explanation: "Risponde a domande = esegue ordini semplici → yellow.",
        path: ["Cammina? → NO", "Respira? → SÌ", "< 30 atti/min? → SÌ", "Polso radiale? → SÌ", "Ordini semplici? → SÌ", "→ yellow"],
    },
    {
        id: "s-giallo-4",
        type: "scenario",
        vignette: "Non cammina per dolore. FR 28/min. Polso radiale apprezzabile. Risponde correttamente a 'come ti chiami?'.",
        correctAnswer: "yellow",
        options: ["green", "yellow", "red"],
        explanation: "FR 28 < 30, polso presente, esegue ordini → yellow. Attenzione: 28 è sotto la soglia.",
        path: ["Cammina? → NO", "Respira? → SÌ", "< 30 atti/min? → SÌ", "Polso radiale? → SÌ", "Ordini semplici? → SÌ", "→ yellow"],
    },
    {
        id: "s-giallo-5",
        type: "scenario",
        vignette: "Paziente con trauma alla spalla, non si rialza. FR 24/min, polso radiale valido. Alla richiesta di chiudere gli occhi, li chiude.",
        correctAnswer: "yellow",
        options: ["green", "yellow", "red"],
        explanation: "Chiudere gli occhi su comando = ordine semplice eseguito → yellow.",
        path: ["Cammina? → NO", "Respira? → SÌ", "< 30 atti/min? → SÌ", "Polso radiale? → SÌ", "Ordini semplici? → SÌ", "→ yellow"],
    },

    // ── Trappole e casi limite ────────────────────────────────────────────────
    {
        id: "s-trap-1",
        type: "what-if",
        vignette: "Paziente con FR 30 atti/min esatti. Lo classifichi come < 30 o > 30?",
        correctAnswer: "red",
        options: ["green", "yellow", "red"],
        hint: "Il protocollo usa '< 30' come soglia. 30 non è minore di 30.",
        explanation: "FR = 30 non è < 30, quindi si considera > 30 → red. Il limite è stretto: solo valori sotto 30 passano al ramo successivo.",
        path: ["FR 30 = non < 30", "→ ramo > 30 atti/min", "→ red"],
    },
    {
        id: "s-trap-2",
        type: "what-if",
        vignette: "Il paziente non cammina ma striscia verso di te usando le braccia. Lo consideri 'deambulante'?",
        correctAnswer: "red",
        options: ["green", "yellow", "red"],
        hint: "Il criterio 'cammina' nel protocollo S.T.A.R.T. significa deambulazione bipede autonoma.",
        explanation: "Strisciare non equivale a camminare. Il paziente non supera il primo step → continua la valutazione dal secondo nodo.",
        path: ["Cammina? → NO (striscia ≠ cammina)", "→ continua valutazione"],
    },
    {
        id: "s-trap-3",
        type: "what-if",
        vignette: "Paziente che non cammina, non respira. Dopo pervietà-cannula inizia a respirare con FR 29/min e polso radiale presente. Esegue ordini. Qual è il codice?",
        correctAnswer: "yellow",
        options: ["green", "yellow", "red"],
        hint: "La cannula ha funzionato: ora valuta il percorso come se respirasse spontaneamente.",
        explanation: "Respira dopo cannula → FR 29 < 30 → polso presente → ordini eseguiti → yellow. La cannula reimmette il paziente nel ramo 'respira' e la valutazione continua normalmente.",
        path: ["Cammina? → NO", "Respira? → NO", "Pervietà-cannula → SÌ", "FR 29 < 30 → SÌ", "Polso? → SÌ", "Ordini? → SÌ", "→ yellow"],
    },
    {
        id: "s-trap-4",
        type: "next-step",
        vignette: "Sei al nodo 'polso radiale'. Il paziente ha una FR di 26/min. Non riesci a sentire il polso radiale ma senti quello carotideo. Cosa fai?",
        correctAnswer: "red",
        options: ["green", "yellow", "red"],
        hint: "Il protocollo S.T.A.R.T. specifica il polso radiale, non quello carotideo.",
        explanation: "Il polso carotideo presente non sostituisce il radiale nel protocollo. Il polso radiale è assente → red. Il polso radiale assente con carotideo presente indica ipotensione severa.",
        path: ["Polso radiale? → NO (carotideo non conta)", "→ red"],
    },
    {
        id: "s-trap-5",
        type: "scenario",
        vignette: "Paziente inconscio con respiro agonico (gasping). Lo classifichi come 'respira'?",
        correctAnswer: "red",
        options: ["green", "yellow", "red"],
        hint: "Il gasping non è respirazione efficace.",
        explanation: "Il gasping non è respiro efficace → il paziente non 'respira' nel senso del protocollo → pervietà-cannula. Se dopo la cannula non riprende un respiro efficace → red.",
        path: ["Cammina? → NO", "Respira? → NO (gasping ≠ respiro)", "Pervietà-cannula →", "se non respira → red"],
    },
    {
        id: "s-trap-6",
        type: "scenario",
        vignette: "Paziente con trauma cranico, non cammina. FR 20/min, polso radiale presente. Risponde alle domande in modo confuso e sconnesso.",
        correctAnswer: "yellow",
        options: ["green", "yellow", "red"],
        hint: "Gli 'ordini semplici' non richiedono risposte coerenti, solo un'azione motoria o verbale in risposta al comando.",
        explanation: "Rispondere, anche in modo confuso, dimostra che recepisce il comando → ordini semplici eseguiti → yellow. La confusione non sposta il codice nel protocollo S.T.A.R.T.",
        path: ["Cammina? → NO", "Respira? → SÌ", "< 30? → SÌ", "Polso? → SÌ", "Ordini? → SÌ (risponde)", "→ yellow"],
    },
    {
        id: "s-trap-7",
        type: "next-step",
        vignette: "Hai già valutato: non cammina, respira, FR 18/min, polso presente. Controlli le emorragie evidenti e fai bendaggio. Qual è il prossimo step del protocollo?",
        correctAnswer: "yellow",
        options: ["green", "yellow", "red"],
        explanation: "Il controllo emorragie è l'azione da eseguire prima di valutare gli ordini semplici nel ramo 'polso presente'. Il passo successivo è: esegue ordini semplici? Il codice finale dipenderà da questa risposta.",
        path: ["... polso presente →", "Controllare emorragie (azione)", "→ Ordini semplici?", "SÌ → yellow / NO → red"],
    },

    // ── Scenari multivariabili ─────────────────────────────────────────────────
    {
        id: "s-multi-1",
        type: "scenario",
        vignette: "Incidente stradale. Uomo sul sedile, non riesce ad alzarsi. FR 12/min, polso radiale debole ma presente. Stringe la mano al comando.",
        correctAnswer: "yellow",
        options: ["green", "yellow", "red"],
        explanation: "FR 12 < 30, polso presente (anche se debole), ordini eseguiti → yellow. La qualità del polso non è un criterio S.T.A.R.T.",
        path: ["Cammina? → NO", "Respira? → SÌ", "< 30? → SÌ", "Polso radiale? → SÌ", "Ordini? → SÌ", "→ yellow"],
    },
    {
        id: "s-multi-2",
        type: "scenario",
        vignette: "Crollo strutturale. Paziente parzialmente sotto le macerie, non può muoversi. Respira a 10/min, polso radiale assente.",
        correctAnswer: "red",
        options: ["green", "yellow", "red"],
        explanation: "FR < 30 ma polso radiale assente → red.",
        path: ["Cammina? → NO", "Respira? → SÌ", "< 30? → SÌ", "Polso radiale? → NO", "→ red"],
    },
    {
        id: "s-multi-3",
        type: "scenario",
        vignette: "Donna distesa, non risponde ai richiami. Non cammina. FR 8/min molto lenta. Polso radiale presente. Non reagisce agli stimoli verbali.",
        correctAnswer: "red",
        options: ["green", "yellow", "red"],
        explanation: "FR 8 < 30, polso presente, ma non esegue ordini → red.",
        path: ["Cammina? → NO", "Respira? → SÌ", "< 30? → SÌ", "Polso? → SÌ", "Ordini? → NO", "→ red"],
    },
    {
        id: "s-multi-4",
        type: "scenario",
        vignette: "Bambino di circa 8 anni seduto per terra, piange forte, si regge il braccio. Non vuole alzarsi ma potrebbe farlo.",
        correctAnswer: "green",
        options: ["green", "yellow", "red"],
        hint: "Può camminare, anche se non vuole?",
        explanation: "Il criterio è la capacità di deambulare, non la volontà. Se il bambino è in grado di camminare (e piange = respira, è cosciente) → green.",
        path: ["Cammina? → SÌ (capacità presente)", "→ green"],
    },
    {
        id: "s-multi-5",
        type: "scenario",
        vignette: "Paziente con trauma toracico, non cammina. La respirazione è rapida e superficiale: stimi 33 atti/min. Forte dolore al petto.",
        correctAnswer: "red",
        options: ["green", "yellow", "red"],
        explanation: "FR 33 > 30 → red. Il dolore e il trauma toracico confermano la gravità ma non cambiano il flusso decisionale.",
        path: ["Cammina? → NO", "Respira? → SÌ", "< 30? → NO", "→ red"],
    },
];